name: coverage

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: snok/.github/workflows/codecov@main
        with:
          source-dir: src/upgrade_type_hints
          pip-cache-key: pip-0
          poetry-cache-key: poetry-0
